// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: worker/protocol.proto

package worker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PBRequestType int32

const (
	PBRequestType_REQUEST_UNSPECIFIED PBRequestType = 0
	PBRequestType_REQUEST_VALIDATE    PBRequestType = 1
	PBRequestType_REQUEST_TEST        PBRequestType = 2
)

// Enum value maps for PBRequestType.
var (
	PBRequestType_name = map[int32]string{
		0: "REQUEST_UNSPECIFIED",
		1: "REQUEST_VALIDATE",
		2: "REQUEST_TEST",
	}
	PBRequestType_value = map[string]int32{
		"REQUEST_UNSPECIFIED": 0,
		"REQUEST_VALIDATE":    1,
		"REQUEST_TEST":        2,
	}
)

func (x PBRequestType) Enum() *PBRequestType {
	p := new(PBRequestType)
	*p = x
	return p
}

func (x PBRequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PBRequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_worker_protocol_proto_enumTypes[0].Descriptor()
}

func (PBRequestType) Type() protoreflect.EnumType {
	return &file_worker_protocol_proto_enumTypes[0]
}

func (x PBRequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PBRequestType.Descriptor instead.
func (PBRequestType) EnumDescriptor() ([]byte, []int) {
	return file_worker_protocol_proto_rawDescGZIP(), []int{0}
}

type PBTestType int32

const (
	PBTestType_TEST_UNSPECIFIED PBTestType = 0
	PBTestType_TEST_LATENCY     PBTestType = 1
	PBTestType_TEST_SPEED       PBTestType = 2
)

// Enum value maps for PBTestType.
var (
	PBTestType_name = map[int32]string{
		0: "TEST_UNSPECIFIED",
		1: "TEST_LATENCY",
		2: "TEST_SPEED",
	}
	PBTestType_value = map[string]int32{
		"TEST_UNSPECIFIED": 0,
		"TEST_LATENCY":     1,
		"TEST_SPEED":       2,
	}
)

func (x PBTestType) Enum() *PBTestType {
	p := new(PBTestType)
	*p = x
	return p
}

func (x PBTestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PBTestType) Descriptor() protoreflect.EnumDescriptor {
	return file_worker_protocol_proto_enumTypes[1].Descriptor()
}

func (PBTestType) Type() protoreflect.EnumType {
	return &file_worker_protocol_proto_enumTypes[1]
}

func (x PBTestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PBTestType.Descriptor instead.
func (PBTestType) EnumDescriptor() ([]byte, []int) {
	return file_worker_protocol_proto_rawDescGZIP(), []int{1}
}

type PBResponseType int32

const (
	PBResponseType_RESPONSE_UNSPECIFIED PBResponseType = 0
	PBResponseType_RESPONSE_VALIDATION  PBResponseType = 1
	PBResponseType_RESPONSE_RESULT      PBResponseType = 2
	PBResponseType_RESPONSE_ERROR       PBResponseType = 3
	PBResponseType_RESPONSE_BUSY        PBResponseType = 4
	PBResponseType_RESPONSE_DONE        PBResponseType = 5
)

// Enum value maps for PBResponseType.
var (
	PBResponseType_name = map[int32]string{
		0: "RESPONSE_UNSPECIFIED",
		1: "RESPONSE_VALIDATION",
		2: "RESPONSE_RESULT",
		3: "RESPONSE_ERROR",
		4: "RESPONSE_BUSY",
		5: "RESPONSE_DONE",
	}
	PBResponseType_value = map[string]int32{
		"RESPONSE_UNSPECIFIED": 0,
		"RESPONSE_VALIDATION":  1,
		"RESPONSE_RESULT":      2,
		"RESPONSE_ERROR":       3,
		"RESPONSE_BUSY":        4,
		"RESPONSE_DONE":        5,
	}
)

func (x PBResponseType) Enum() *PBResponseType {
	p := new(PBResponseType)
	*p = x
	return p
}

func (x PBResponseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PBResponseType) Descriptor() protoreflect.EnumDescriptor {
	return file_worker_protocol_proto_enumTypes[2].Descriptor()
}

func (PBResponseType) Type() protoreflect.EnumType {
	return &file_worker_protocol_proto_enumTypes[2]
}

func (x PBResponseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PBResponseType.Descriptor instead.
func (PBResponseType) EnumDescriptor() ([]byte, []int) {
	return file_worker_protocol_proto_rawDescGZIP(), []int{2}
}

type PBSpeedTestMode int32

const (
	PBSpeedTestMode_SPEED_UNSPECIFIED PBSpeedTestMode = 0
	PBSpeedTestMode_SPEED_DOWNLOAD    PBSpeedTestMode = 1
	PBSpeedTestMode_SPEED_UPLOAD      PBSpeedTestMode = 2
)

// Enum value maps for PBSpeedTestMode.
var (
	PBSpeedTestMode_name = map[int32]string{
		0: "SPEED_UNSPECIFIED",
		1: "SPEED_DOWNLOAD",
		2: "SPEED_UPLOAD",
	}
	PBSpeedTestMode_value = map[string]int32{
		"SPEED_UNSPECIFIED": 0,
		"SPEED_DOWNLOAD":    1,
		"SPEED_UPLOAD":      2,
	}
)

func (x PBSpeedTestMode) Enum() *PBSpeedTestMode {
	p := new(PBSpeedTestMode)
	*p = x
	return p
}

func (x PBSpeedTestMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PBSpeedTestMode) Descriptor() protoreflect.EnumDescriptor {
	return file_worker_protocol_proto_enumTypes[3].Descriptor()
}

func (PBSpeedTestMode) Type() protoreflect.EnumType {
	return &file_worker_protocol_proto_enumTypes[3]
}

func (x PBSpeedTestMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PBSpeedTestMode.Descriptor instead.
func (PBSpeedTestMode) EnumDescriptor() ([]byte, []int) {
	return file_worker_protocol_proto_rawDescGZIP(), []int{3}
}

type PBCoreInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBCoreInfo) Reset() {
	*x = PBCoreInfo{}
	mi := &file_worker_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBCoreInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBCoreInfo) ProtoMessage() {}

func (x *PBCoreInfo) ProtoReflect() protoreflect.Message {
	mi := &file_worker_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBCoreInfo.ProtoReflect.Descriptor instead.
func (*PBCoreInfo) Descriptor() ([]byte, []int) {
	return file_worker_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *PBCoreInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PBCoreInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type PBValidationError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           []byte                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBValidationError) Reset() {
	*x = PBValidationError{}
	mi := &file_worker_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBValidationError) ProtoMessage() {}

func (x *PBValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_worker_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBValidationError.ProtoReflect.Descriptor instead.
func (*PBValidationError) Descriptor() ([]byte, []int) {
	return file_worker_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *PBValidationError) GetTag() []byte {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *PBValidationError) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PBResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Type             PBResponseType         `protobuf:"varint,1,opt,name=type,proto3,enum=worker.PBResponseType" json:"type,omitempty"`
	ValidationErrors []*PBValidationError   `protobuf:"bytes,2,rep,name=validation_errors,json=validationErrors,proto3" json:"validation_errors,omitempty"`
	Tag              []byte                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	Error            string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	LatencyMs        int64                  `protobuf:"varint,5,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Speed            float64                `protobuf:"fixed64,6,opt,name=speed,proto3" json:"speed,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PBResponse) Reset() {
	*x = PBResponse{}
	mi := &file_worker_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBResponse) ProtoMessage() {}

func (x *PBResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBResponse.ProtoReflect.Descriptor instead.
func (*PBResponse) Descriptor() ([]byte, []int) {
	return file_worker_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *PBResponse) GetType() PBResponseType {
	if x != nil {
		return x.Type
	}
	return PBResponseType_RESPONSE_UNSPECIFIED
}

func (x *PBResponse) GetValidationErrors() []*PBValidationError {
	if x != nil {
		return x.ValidationErrors
	}
	return nil
}

func (x *PBResponse) GetTag() []byte {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *PBResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PBResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *PBResponse) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type PBLatencyTestSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestUrl       string                 `protobuf:"bytes,1,opt,name=test_url,json=testUrl,proto3" json:"test_url,omitempty"`
	RawRequest    []byte                 `protobuf:"bytes,2,opt,name=raw_request,json=rawRequest,proto3" json:"raw_request,omitempty"`
	TimeoutNanos  int64                  `protobuf:"varint,3,opt,name=timeout_nanos,json=timeoutNanos,proto3" json:"timeout_nanos,omitempty"`
	Concurrency   int32                  `protobuf:"varint,4,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBLatencyTestSettings) Reset() {
	*x = PBLatencyTestSettings{}
	mi := &file_worker_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBLatencyTestSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBLatencyTestSettings) ProtoMessage() {}

func (x *PBLatencyTestSettings) ProtoReflect() protoreflect.Message {
	mi := &file_worker_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBLatencyTestSettings.ProtoReflect.Descriptor instead.
func (*PBLatencyTestSettings) Descriptor() ([]byte, []int) {
	return file_worker_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *PBLatencyTestSettings) GetTestUrl() string {
	if x != nil {
		return x.TestUrl
	}
	return ""
}

func (x *PBLatencyTestSettings) GetRawRequest() []byte {
	if x != nil {
		return x.RawRequest
	}
	return nil
}

func (x *PBLatencyTestSettings) GetTimeoutNanos() int64 {
	if x != nil {
		return x.TimeoutNanos
	}
	return 0
}

func (x *PBLatencyTestSettings) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

type PBSpeedTestSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          PBSpeedTestMode        `protobuf:"varint,1,opt,name=mode,proto3,enum=worker.PBSpeedTestMode" json:"mode,omitempty"`
	TestUrl       string                 `protobuf:"bytes,2,opt,name=test_url,json=testUrl,proto3" json:"test_url,omitempty"`
	RawRequest    []byte                 `protobuf:"bytes,3,opt,name=raw_request,json=rawRequest,proto3" json:"raw_request,omitempty"`
	TimeoutNanos  int64                  `protobuf:"varint,4,opt,name=timeout_nanos,json=timeoutNanos,proto3" json:"timeout_nanos,omitempty"`
	TargetBytes   int64                  `protobuf:"varint,5,opt,name=target_bytes,json=targetBytes,proto3" json:"target_bytes,omitempty"`
	Concurrency   int32                  `protobuf:"varint,6,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBSpeedTestSettings) Reset() {
	*x = PBSpeedTestSettings{}
	mi := &file_worker_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBSpeedTestSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBSpeedTestSettings) ProtoMessage() {}

func (x *PBSpeedTestSettings) ProtoReflect() protoreflect.Message {
	mi := &file_worker_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBSpeedTestSettings.ProtoReflect.Descriptor instead.
func (*PBSpeedTestSettings) Descriptor() ([]byte, []int) {
	return file_worker_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *PBSpeedTestSettings) GetMode() PBSpeedTestMode {
	if x != nil {
		return x.Mode
	}
	return PBSpeedTestMode_SPEED_UNSPECIFIED
}

func (x *PBSpeedTestSettings) GetTestUrl() string {
	if x != nil {
		return x.TestUrl
	}
	return ""
}

func (x *PBSpeedTestSettings) GetRawRequest() []byte {
	if x != nil {
		return x.RawRequest
	}
	return nil
}

func (x *PBSpeedTestSettings) GetTimeoutNanos() int64 {
	if x != nil {
		return x.TimeoutNanos
	}
	return 0
}

func (x *PBSpeedTestSettings) GetTargetBytes() int64 {
	if x != nil {
		return x.TargetBytes
	}
	return 0
}

func (x *PBSpeedTestSettings) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

type PBObfsConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          []byte                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Password      []byte                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBObfsConfig) Reset() {
	*x = PBObfsConfig{}
	mi := &file_worker_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBObfsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBObfsConfig) ProtoMessage() {}

func (x *PBObfsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_worker_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBObfsConfig.ProtoReflect.Descriptor instead.
func (*PBObfsConfig) Descriptor() ([]byte, []int) {
	return file_worker_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *PBObfsConfig) GetType() []byte {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *PBObfsConfig) GetPassword() []byte {
	if x != nil {
		return x.Password
	}
	return nil
}

type PBVLESSSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Flow          []byte                 `protobuf:"bytes,2,opt,name=flow,proto3" json:"flow,omitempty"`
	Encryption    []byte                 `protobuf:"bytes,3,opt,name=encryption,proto3" json:"encryption,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBVLESSSettings) Reset() {
	*x = PBVLESSSettings{}
	mi := &file_worker_protocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBVLESSSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBVLESSSettings) ProtoMessage() {}

func (x *PBVLESSSettings) ProtoReflect() protoreflect.Message {
	mi := &file_worker_protocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBVLESSSettings.ProtoReflect.Descriptor instead.
func (*PBVLESSSettings) Descriptor() ([]byte, []int) {
	return file_worker_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *PBVLESSSettings) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *PBVLESSSettings) GetFlow() []byte {
	if x != nil {
		return x.Flow
	}
	return nil
}

func (x *PBVLESSSettings) GetEncryption() []byte {
	if x != nil {
		return x.Encryption
	}
	return nil
}

type PBTrojanSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      []byte                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBTrojanSettings) Reset() {
	*x = PBTrojanSettings{}
	mi := &file_worker_protocol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBTrojanSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBTrojanSettings) ProtoMessage() {}

func (x *PBTrojanSettings) ProtoReflect() protoreflect.Message {
	mi := &file_worker_protocol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBTrojanSettings.ProtoReflect.Descriptor instead.
func (*PBTrojanSettings) Descriptor() ([]byte, []int) {
	return file_worker_protocol_proto_rawDescGZIP(), []int{7}
}

func (x *PBTrojanSettings) GetPassword() []byte {
	if x != nil {
		return x.Password
	}
	return nil
}

type PBVMessSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	AlterId       int32                  `protobuf:"varint,2,opt,name=alter_id,json=alterId,proto3" json:"alter_id,omitempty"`
	Security      []byte                 `protobuf:"bytes,3,opt,name=security,proto3" json:"security,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBVMessSettings) Reset() {
	*x = PBVMessSettings{}
	mi := &file_worker_protocol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBVMessSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBVMessSettings) ProtoMessage() {}

func (x *PBVMessSettings) ProtoReflect() protoreflect.Message {
	mi := &file_worker_protocol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBVMessSettings.ProtoReflect.Descriptor instead.
func (*PBVMessSettings) Descriptor() ([]byte, []int) {
	return file_worker_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *PBVMessSettings) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *PBVMessSettings) GetAlterId() int32 {
	if x != nil {
		return x.AlterId
	}
	return 0
}

func (x *PBVMessSettings) GetSecurity() []byte {
	if x != nil {
		return x.Security
	}
	return nil
}

type PBShadowsocksSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        []byte                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Password      []byte                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBShadowsocksSettings) Reset() {
	*x = PBShadowsocksSettings{}
	mi := &file_worker_protocol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBShadowsocksSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBShadowsocksSettings) ProtoMessage() {}

func (x *PBShadowsocksSettings) ProtoReflect() protoreflect.Message {
	mi := &file_worker_protocol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBShadowsocksSettings.ProtoReflect.Descriptor instead.
func (*PBShadowsocksSettings) Descriptor() ([]byte, []int) {
	return file_worker_protocol_proto_rawDescGZIP(), []int{9}
}

func (x *PBShadowsocksSettings) GetMethod() []byte {
	if x != nil {
		return x.Method
	}
	return nil
}

func (x *PBShadowsocksSettings) GetPassword() []byte {
	if x != nil {
		return x.Password
	}
	return nil
}

type PBHysteria2Settings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      []byte                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	Obfs          *PBObfsConfig          `protobuf:"bytes,2,opt,name=obfs,proto3" json:"obfs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBHysteria2Settings) Reset() {
	*x = PBHysteria2Settings{}
	mi := &file_worker_protocol_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBHysteria2Settings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBHysteria2Settings) ProtoMessage() {}

func (x *PBHysteria2Settings) ProtoReflect() protoreflect.Message {
	mi := &file_worker_protocol_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBHysteria2Settings.ProtoReflect.Descriptor instead.
func (*PBHysteria2Settings) Descriptor() ([]byte, []int) {
	return file_worker_protocol_proto_rawDescGZIP(), []int{10}
}

func (x *PBHysteria2Settings) GetPassword() []byte {
	if x != nil {
		return x.Password
	}
	return nil
}

func (x *PBHysteria2Settings) GetObfs() *PBObfsConfig {
	if x != nil {
		return x.Obfs
	}
	return nil
}

type PBWireguardPeer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Endpoint      []byte                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBWireguardPeer) Reset() {
	*x = PBWireguardPeer{}
	mi := &file_worker_protocol_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBWireguardPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBWireguardPeer) ProtoMessage() {}

func (x *PBWireguardPeer) ProtoReflect() protoreflect.Message {
	mi := &file_worker_protocol_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBWireguardPeer.ProtoReflect.Descriptor instead.
func (*PBWireguardPeer) Descriptor() ([]byte, []int) {
	return file_worker_protocol_proto_rawDescGZIP(), []int{11}
}

func (x *PBWireguardPeer) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *PBWireguardPeer) GetEndpoint() []byte {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

type PBWireguardSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretKey     []byte                 `protobuf:"bytes,1,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	Address       [][]byte               `protobuf:"bytes,2,rep,name=address,proto3" json:"address,omitempty"`
	Peers         []*PBWireguardPeer     `protobuf:"bytes,3,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBWireguardSettings) Reset() {
	*x = PBWireguardSettings{}
	mi := &file_worker_protocol_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBWireguardSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBWireguardSettings) ProtoMessage() {}

func (x *PBWireguardSettings) ProtoReflect() protoreflect.Message {
	mi := &file_worker_protocol_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBWireguardSettings.ProtoReflect.Descriptor instead.
func (*PBWireguardSettings) Descriptor() ([]byte, []int) {
	return file_worker_protocol_proto_rawDescGZIP(), []int{12}
}

func (x *PBWireguardSettings) GetSecretKey() []byte {
	if x != nil {
		return x.SecretKey
	}
	return nil
}

func (x *PBWireguardSettings) GetAddress() [][]byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *PBWireguardSettings) GetPeers() []*PBWireguardPeer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type PBSocksSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       []byte                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	User          []byte                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Pass          []byte                 `protobuf:"bytes,3,opt,name=pass,proto3" json:"pass,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBSocksSettings) Reset() {
	*x = PBSocksSettings{}
	mi := &file_worker_protocol_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBSocksSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBSocksSettings) ProtoMessage() {}

func (x *PBSocksSettings) ProtoReflect() protoreflect.Message {
	mi := &file_worker_protocol_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBSocksSettings.ProtoReflect.Descriptor instead.
func (*PBSocksSettings) Descriptor() ([]byte, []int) {
	return file_worker_protocol_proto_rawDescGZIP(), []int{13}
}

func (x *PBSocksSettings) GetVersion() []byte {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *PBSocksSettings) GetUser() []byte {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *PBSocksSettings) GetPass() []byte {
	if x != nil {
		return x.Pass
	}
	return nil
}

type PBHTTPSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          []byte                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Pass          []byte                 `protobuf:"bytes,2,opt,name=pass,proto3" json:"pass,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBHTTPSettings) Reset() {
	*x = PBHTTPSettings{}
	mi := &file_worker_protocol_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBHTTPSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBHTTPSettings) ProtoMessage() {}

func (x *PBHTTPSettings) ProtoReflect() protoreflect.Message {
	mi := &file_worker_protocol_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBHTTPSettings.ProtoReflect.Descriptor instead.
func (*PBHTTPSettings) Descriptor() ([]byte, []int) {
	return file_worker_protocol_proto_rawDescGZIP(), []int{14}
}

func (x *PBHTTPSettings) GetUser() []byte {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *PBHTTPSettings) GetPass() []byte {
	if x != nil {
		return x.Pass
	}
	return nil
}

type PBVLiteSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      []byte                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBVLiteSettings) Reset() {
	*x = PBVLiteSettings{}
	mi := &file_worker_protocol_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBVLiteSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBVLiteSettings) ProtoMessage() {}

func (x *PBVLiteSettings) ProtoReflect() protoreflect.Message {
	mi := &file_worker_protocol_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBVLiteSettings.ProtoReflect.Descriptor instead.
func (*PBVLiteSettings) Descriptor() ([]byte, []int) {
	return file_worker_protocol_proto_rawDescGZIP(), []int{15}
}

func (x *PBVLiteSettings) GetPassword() []byte {
	if x != nil {
		return x.Password
	}
	return nil
}

type PBRealityConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	ShortId       []byte                 `protobuf:"bytes,2,opt,name=short_id,json=shortId,proto3" json:"short_id,omitempty"`
	SpiderX       []byte                 `protobuf:"bytes,3,opt,name=spider_x,json=spiderX,proto3" json:"spider_x,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBRealityConfig) Reset() {
	*x = PBRealityConfig{}
	mi := &file_worker_protocol_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBRealityConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBRealityConfig) ProtoMessage() {}

func (x *PBRealityConfig) ProtoReflect() protoreflect.Message {
	mi := &file_worker_protocol_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBRealityConfig.ProtoReflect.Descriptor instead.
func (*PBRealityConfig) Descriptor() ([]byte, []int) {
	return file_worker_protocol_proto_rawDescGZIP(), []int{16}
}

func (x *PBRealityConfig) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *PBRealityConfig) GetShortId() []byte {
	if x != nil {
		return x.ShortId
	}
	return nil
}

func (x *PBRealityConfig) GetSpiderX() []byte {
	if x != nil {
		return x.SpiderX
	}
	return nil
}

type PBECHConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        [][]byte               `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBECHConfig) Reset() {
	*x = PBECHConfig{}
	mi := &file_worker_protocol_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBECHConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBECHConfig) ProtoMessage() {}

func (x *PBECHConfig) ProtoReflect() protoreflect.Message {
	mi := &file_worker_protocol_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBECHConfig.ProtoReflect.Descriptor instead.
func (*PBECHConfig) Descriptor() ([]byte, []int) {
	return file_worker_protocol_proto_rawDescGZIP(), []int{17}
}

func (x *PBECHConfig) GetConfig() [][]byte {
	if x != nil {
		return x.Config
	}
	return nil
}

type PBTLSConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ServerName    []byte                 `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Insecure      bool                   `protobuf:"varint,3,opt,name=insecure,proto3" json:"insecure,omitempty"`
	Alpn          [][]byte               `protobuf:"bytes,4,rep,name=alpn,proto3" json:"alpn,omitempty"`
	Fingerprint   []byte                 `protobuf:"bytes,5,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Reality       *PBRealityConfig       `protobuf:"bytes,6,opt,name=reality,proto3" json:"reality,omitempty"`
	Ech           *PBECHConfig           `protobuf:"bytes,7,opt,name=ech,proto3" json:"ech,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBTLSConfig) Reset() {
	*x = PBTLSConfig{}
	mi := &file_worker_protocol_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBTLSConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBTLSConfig) ProtoMessage() {}

func (x *PBTLSConfig) ProtoReflect() protoreflect.Message {
	mi := &file_worker_protocol_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBTLSConfig.ProtoReflect.Descriptor instead.
func (*PBTLSConfig) Descriptor() ([]byte, []int) {
	return file_worker_protocol_proto_rawDescGZIP(), []int{18}
}

func (x *PBTLSConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *PBTLSConfig) GetServerName() []byte {
	if x != nil {
		return x.ServerName
	}
	return nil
}

func (x *PBTLSConfig) GetInsecure() bool {
	if x != nil {
		return x.Insecure
	}
	return false
}

func (x *PBTLSConfig) GetAlpn() [][]byte {
	if x != nil {
		return x.Alpn
	}
	return nil
}

func (x *PBTLSConfig) GetFingerprint() []byte {
	if x != nil {
		return x.Fingerprint
	}
	return nil
}

func (x *PBTLSConfig) GetReality() *PBRealityConfig {
	if x != nil {
		return x.Reality
	}
	return nil
}

func (x *PBTLSConfig) GetEch() *PBECHConfig {
	if x != nil {
		return x.Ech
	}
	return nil
}

type PBHTTPConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          [][]byte               `protobuf:"bytes,1,rep,name=host,proto3" json:"host,omitempty"`
	Path          []byte                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Method        []byte                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBHTTPConfig) Reset() {
	*x = PBHTTPConfig{}
	mi := &file_worker_protocol_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBHTTPConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBHTTPConfig) ProtoMessage() {}

func (x *PBHTTPConfig) ProtoReflect() protoreflect.Message {
	mi := &file_worker_protocol_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBHTTPConfig.ProtoReflect.Descriptor instead.
func (*PBHTTPConfig) Descriptor() ([]byte, []int) {
	return file_worker_protocol_proto_rawDescGZIP(), []int{19}
}

func (x *PBHTTPConfig) GetHost() [][]byte {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *PBHTTPConfig) GetPath() []byte {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *PBHTTPConfig) GetMethod() []byte {
	if x != nil {
		return x.Method
	}
	return nil
}

type PBWebSocketConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          []byte                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Host          []byte                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBWebSocketConfig) Reset() {
	*x = PBWebSocketConfig{}
	mi := &file_worker_protocol_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBWebSocketConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBWebSocketConfig) ProtoMessage() {}

func (x *PBWebSocketConfig) ProtoReflect() protoreflect.Message {
	mi := &file_worker_protocol_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBWebSocketConfig.ProtoReflect.Descriptor instead.
func (*PBWebSocketConfig) Descriptor() ([]byte, []int) {
	return file_worker_protocol_proto_rawDescGZIP(), []int{20}
}

func (x *PBWebSocketConfig) GetPath() []byte {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *PBWebSocketConfig) GetHost() []byte {
	if x != nil {
		return x.Host
	}
	return nil
}

type PBQUICConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBQUICConfig) Reset() {
	*x = PBQUICConfig{}
	mi := &file_worker_protocol_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBQUICConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBQUICConfig) ProtoMessage() {}

func (x *PBQUICConfig) ProtoReflect() protoreflect.Message {
	mi := &file_worker_protocol_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBQUICConfig.ProtoReflect.Descriptor instead.
func (*PBQUICConfig) Descriptor() ([]byte, []int) {
	return file_worker_protocol_proto_rawDescGZIP(), []int{21}
}

type PBGRPCConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   []byte                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBGRPCConfig) Reset() {
	*x = PBGRPCConfig{}
	mi := &file_worker_protocol_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBGRPCConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBGRPCConfig) ProtoMessage() {}

func (x *PBGRPCConfig) ProtoReflect() protoreflect.Message {
	mi := &file_worker_protocol_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBGRPCConfig.ProtoReflect.Descriptor instead.
func (*PBGRPCConfig) Descriptor() ([]byte, []int) {
	return file_worker_protocol_proto_rawDescGZIP(), []int{22}
}

func (x *PBGRPCConfig) GetServiceName() []byte {
	if x != nil {
		return x.ServiceName
	}
	return nil
}

type PBHTTPUpgradeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          []byte                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Path          []byte                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBHTTPUpgradeConfig) Reset() {
	*x = PBHTTPUpgradeConfig{}
	mi := &file_worker_protocol_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBHTTPUpgradeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBHTTPUpgradeConfig) ProtoMessage() {}

func (x *PBHTTPUpgradeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_worker_protocol_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBHTTPUpgradeConfig.ProtoReflect.Descriptor instead.
func (*PBHTTPUpgradeConfig) Descriptor() ([]byte, []int) {
	return file_worker_protocol_proto_rawDescGZIP(), []int{23}
}

func (x *PBHTTPUpgradeConfig) GetHost() []byte {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *PBHTTPUpgradeConfig) GetPath() []byte {
	if x != nil {
		return x.Path
	}
	return nil
}

type PBXHTTPConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          []byte                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Path          []byte                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Mode          []byte                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Extra         map[string][]byte      `protobuf:"bytes,4,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBXHTTPConfig) Reset() {
	*x = PBXHTTPConfig{}
	mi := &file_worker_protocol_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBXHTTPConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBXHTTPConfig) ProtoMessage() {}

func (x *PBXHTTPConfig) ProtoReflect() protoreflect.Message {
	mi := &file_worker_protocol_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBXHTTPConfig.ProtoReflect.Descriptor instead.
func (*PBXHTTPConfig) Descriptor() ([]byte, []int) {
	return file_worker_protocol_proto_rawDescGZIP(), []int{24}
}

func (x *PBXHTTPConfig) GetHost() []byte {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *PBXHTTPConfig) GetPath() []byte {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *PBXHTTPConfig) GetMode() []byte {
	if x != nil {
		return x.Mode
	}
	return nil
}

func (x *PBXHTTPConfig) GetExtra() map[string][]byte {
	if x != nil {
		return x.Extra
	}
	return nil
}

type PBSplitHTTPConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          []byte                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Path          []byte                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBSplitHTTPConfig) Reset() {
	*x = PBSplitHTTPConfig{}
	mi := &file_worker_protocol_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBSplitHTTPConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBSplitHTTPConfig) ProtoMessage() {}

func (x *PBSplitHTTPConfig) ProtoReflect() protoreflect.Message {
	mi := &file_worker_protocol_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBSplitHTTPConfig.ProtoReflect.Descriptor instead.
func (*PBSplitHTTPConfig) Descriptor() ([]byte, []int) {
	return file_worker_protocol_proto_rawDescGZIP(), []int{25}
}

func (x *PBSplitHTTPConfig) GetHost() []byte {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *PBSplitHTTPConfig) GetPath() []byte {
	if x != nil {
		return x.Path
	}
	return nil
}

type PBKCPConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seed          []byte                 `protobuf:"bytes,1,opt,name=seed,proto3" json:"seed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBKCPConfig) Reset() {
	*x = PBKCPConfig{}
	mi := &file_worker_protocol_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBKCPConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBKCPConfig) ProtoMessage() {}

func (x *PBKCPConfig) ProtoReflect() protoreflect.Message {
	mi := &file_worker_protocol_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBKCPConfig.ProtoReflect.Descriptor instead.
func (*PBKCPConfig) Descriptor() ([]byte, []int) {
	return file_worker_protocol_proto_rawDescGZIP(), []int{26}
}

func (x *PBKCPConfig) GetSeed() []byte {
	if x != nil {
		return x.Seed
	}
	return nil
}

type PBTransportConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Http          *PBHTTPConfig          `protobuf:"bytes,2,opt,name=http,proto3" json:"http,omitempty"`
	Websocket     *PBWebSocketConfig     `protobuf:"bytes,3,opt,name=websocket,proto3" json:"websocket,omitempty"`
	Quic          *PBQUICConfig          `protobuf:"bytes,4,opt,name=quic,proto3" json:"quic,omitempty"`
	Grpc          *PBGRPCConfig          `protobuf:"bytes,5,opt,name=grpc,proto3" json:"grpc,omitempty"`
	HttpUpgrade   *PBHTTPUpgradeConfig   `protobuf:"bytes,6,opt,name=http_upgrade,json=httpUpgrade,proto3" json:"http_upgrade,omitempty"`
	Xhttp         *PBXHTTPConfig         `protobuf:"bytes,7,opt,name=xhttp,proto3" json:"xhttp,omitempty"`
	SplitHttp     *PBSplitHTTPConfig     `protobuf:"bytes,8,opt,name=split_http,json=splitHttp,proto3" json:"split_http,omitempty"`
	Kcp           *PBKCPConfig           `protobuf:"bytes,9,opt,name=kcp,proto3" json:"kcp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBTransportConfig) Reset() {
	*x = PBTransportConfig{}
	mi := &file_worker_protocol_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBTransportConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBTransportConfig) ProtoMessage() {}

func (x *PBTransportConfig) ProtoReflect() protoreflect.Message {
	mi := &file_worker_protocol_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBTransportConfig.ProtoReflect.Descriptor instead.
func (*PBTransportConfig) Descriptor() ([]byte, []int) {
	return file_worker_protocol_proto_rawDescGZIP(), []int{27}
}

func (x *PBTransportConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PBTransportConfig) GetHttp() *PBHTTPConfig {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *PBTransportConfig) GetWebsocket() *PBWebSocketConfig {
	if x != nil {
		return x.Websocket
	}
	return nil
}

func (x *PBTransportConfig) GetQuic() *PBQUICConfig {
	if x != nil {
		return x.Quic
	}
	return nil
}

func (x *PBTransportConfig) GetGrpc() *PBGRPCConfig {
	if x != nil {
		return x.Grpc
	}
	return nil
}

func (x *PBTransportConfig) GetHttpUpgrade() *PBHTTPUpgradeConfig {
	if x != nil {
		return x.HttpUpgrade
	}
	return nil
}

func (x *PBTransportConfig) GetXhttp() *PBXHTTPConfig {
	if x != nil {
		return x.Xhttp
	}
	return nil
}

func (x *PBTransportConfig) GetSplitHttp() *PBSplitHTTPConfig {
	if x != nil {
		return x.SplitHttp
	}
	return nil
}

func (x *PBTransportConfig) GetKcp() *PBKCPConfig {
	if x != nil {
		return x.Kcp
	}
	return nil
}

type PBOutboundConfig struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Tag       []byte                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Type      []byte                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Server    []byte                 `protobuf:"bytes,3,opt,name=server,proto3" json:"server,omitempty"`
	Port      uint32                 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Tls       *PBTLSConfig           `protobuf:"bytes,5,opt,name=tls,proto3" json:"tls,omitempty"`
	Transport *PBTransportConfig     `protobuf:"bytes,6,opt,name=transport,proto3" json:"transport,omitempty"`
	// Types that are valid to be assigned to Settings:
	//
	//	*PBOutboundConfig_Vless
	//	*PBOutboundConfig_Trojan
	//	*PBOutboundConfig_Vmess
	//	*PBOutboundConfig_Shadowsocks
	//	*PBOutboundConfig_Hysteria2
	//	*PBOutboundConfig_Wireguard
	//	*PBOutboundConfig_Socks
	//	*PBOutboundConfig_Http
	//	*PBOutboundConfig_Vlite
	Settings      isPBOutboundConfig_Settings `protobuf_oneof:"settings"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBOutboundConfig) Reset() {
	*x = PBOutboundConfig{}
	mi := &file_worker_protocol_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBOutboundConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBOutboundConfig) ProtoMessage() {}

func (x *PBOutboundConfig) ProtoReflect() protoreflect.Message {
	mi := &file_worker_protocol_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBOutboundConfig.ProtoReflect.Descriptor instead.
func (*PBOutboundConfig) Descriptor() ([]byte, []int) {
	return file_worker_protocol_proto_rawDescGZIP(), []int{28}
}

func (x *PBOutboundConfig) GetTag() []byte {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *PBOutboundConfig) GetType() []byte {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *PBOutboundConfig) GetServer() []byte {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *PBOutboundConfig) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *PBOutboundConfig) GetTls() *PBTLSConfig {
	if x != nil {
		return x.Tls
	}
	return nil
}

func (x *PBOutboundConfig) GetTransport() *PBTransportConfig {
	if x != nil {
		return x.Transport
	}
	return nil
}

func (x *PBOutboundConfig) GetSettings() isPBOutboundConfig_Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *PBOutboundConfig) GetVless() *PBVLESSSettings {
	if x != nil {
		if x, ok := x.Settings.(*PBOutboundConfig_Vless); ok {
			return x.Vless
		}
	}
	return nil
}

func (x *PBOutboundConfig) GetTrojan() *PBTrojanSettings {
	if x != nil {
		if x, ok := x.Settings.(*PBOutboundConfig_Trojan); ok {
			return x.Trojan
		}
	}
	return nil
}

func (x *PBOutboundConfig) GetVmess() *PBVMessSettings {
	if x != nil {
		if x, ok := x.Settings.(*PBOutboundConfig_Vmess); ok {
			return x.Vmess
		}
	}
	return nil
}

func (x *PBOutboundConfig) GetShadowsocks() *PBShadowsocksSettings {
	if x != nil {
		if x, ok := x.Settings.(*PBOutboundConfig_Shadowsocks); ok {
			return x.Shadowsocks
		}
	}
	return nil
}

func (x *PBOutboundConfig) GetHysteria2() *PBHysteria2Settings {
	if x != nil {
		if x, ok := x.Settings.(*PBOutboundConfig_Hysteria2); ok {
			return x.Hysteria2
		}
	}
	return nil
}

func (x *PBOutboundConfig) GetWireguard() *PBWireguardSettings {
	if x != nil {
		if x, ok := x.Settings.(*PBOutboundConfig_Wireguard); ok {
			return x.Wireguard
		}
	}
	return nil
}

func (x *PBOutboundConfig) GetSocks() *PBSocksSettings {
	if x != nil {
		if x, ok := x.Settings.(*PBOutboundConfig_Socks); ok {
			return x.Socks
		}
	}
	return nil
}

func (x *PBOutboundConfig) GetHttp() *PBHTTPSettings {
	if x != nil {
		if x, ok := x.Settings.(*PBOutboundConfig_Http); ok {
			return x.Http
		}
	}
	return nil
}

func (x *PBOutboundConfig) GetVlite() *PBVLiteSettings {
	if x != nil {
		if x, ok := x.Settings.(*PBOutboundConfig_Vlite); ok {
			return x.Vlite
		}
	}
	return nil
}

type isPBOutboundConfig_Settings interface {
	isPBOutboundConfig_Settings()
}

type PBOutboundConfig_Vless struct {
	Vless *PBVLESSSettings `protobuf:"bytes,7,opt,name=vless,proto3,oneof"`
}

type PBOutboundConfig_Trojan struct {
	Trojan *PBTrojanSettings `protobuf:"bytes,8,opt,name=trojan,proto3,oneof"`
}

type PBOutboundConfig_Vmess struct {
	Vmess *PBVMessSettings `protobuf:"bytes,9,opt,name=vmess,proto3,oneof"`
}

type PBOutboundConfig_Shadowsocks struct {
	Shadowsocks *PBShadowsocksSettings `protobuf:"bytes,10,opt,name=shadowsocks,proto3,oneof"`
}

type PBOutboundConfig_Hysteria2 struct {
	Hysteria2 *PBHysteria2Settings `protobuf:"bytes,11,opt,name=hysteria2,proto3,oneof"`
}

type PBOutboundConfig_Wireguard struct {
	Wireguard *PBWireguardSettings `protobuf:"bytes,12,opt,name=wireguard,proto3,oneof"`
}

type PBOutboundConfig_Socks struct {
	Socks *PBSocksSettings `protobuf:"bytes,13,opt,name=socks,proto3,oneof"`
}

type PBOutboundConfig_Http struct {
	Http *PBHTTPSettings `protobuf:"bytes,14,opt,name=http,proto3,oneof"`
}

type PBOutboundConfig_Vlite struct {
	Vlite *PBVLiteSettings `protobuf:"bytes,15,opt,name=vlite,proto3,oneof"`
}

func (*PBOutboundConfig_Vless) isPBOutboundConfig_Settings() {}

func (*PBOutboundConfig_Trojan) isPBOutboundConfig_Settings() {}

func (*PBOutboundConfig_Vmess) isPBOutboundConfig_Settings() {}

func (*PBOutboundConfig_Shadowsocks) isPBOutboundConfig_Settings() {}

func (*PBOutboundConfig_Hysteria2) isPBOutboundConfig_Settings() {}

func (*PBOutboundConfig_Wireguard) isPBOutboundConfig_Settings() {}

func (*PBOutboundConfig_Socks) isPBOutboundConfig_Settings() {}

func (*PBOutboundConfig_Http) isPBOutboundConfig_Settings() {}

func (*PBOutboundConfig_Vlite) isPBOutboundConfig_Settings() {}

type PBRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Type     PBRequestType          `protobuf:"varint,1,opt,name=type,proto3,enum=worker.PBRequestType" json:"type,omitempty"`
	TestType PBTestType             `protobuf:"varint,2,opt,name=test_type,json=testType,proto3,enum=worker.PBTestType" json:"test_type,omitempty"`
	Configs  []*PBOutboundConfig    `protobuf:"bytes,3,rep,name=configs,proto3" json:"configs,omitempty"`
	Tags     [][]byte               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	// Types that are valid to be assigned to Settings:
	//
	//	*PBRequest_LatencySettings
	//	*PBRequest_SpeedSettings
	Settings      isPBRequest_Settings `protobuf_oneof:"settings"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBRequest) Reset() {
	*x = PBRequest{}
	mi := &file_worker_protocol_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBRequest) ProtoMessage() {}

func (x *PBRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_protocol_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBRequest.ProtoReflect.Descriptor instead.
func (*PBRequest) Descriptor() ([]byte, []int) {
	return file_worker_protocol_proto_rawDescGZIP(), []int{29}
}

func (x *PBRequest) GetType() PBRequestType {
	if x != nil {
		return x.Type
	}
	return PBRequestType_REQUEST_UNSPECIFIED
}

func (x *PBRequest) GetTestType() PBTestType {
	if x != nil {
		return x.TestType
	}
	return PBTestType_TEST_UNSPECIFIED
}

func (x *PBRequest) GetConfigs() []*PBOutboundConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

func (x *PBRequest) GetTags() [][]byte {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PBRequest) GetSettings() isPBRequest_Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *PBRequest) GetLatencySettings() *PBLatencyTestSettings {
	if x != nil {
		if x, ok := x.Settings.(*PBRequest_LatencySettings); ok {
			return x.LatencySettings
		}
	}
	return nil
}

func (x *PBRequest) GetSpeedSettings() *PBSpeedTestSettings {
	if x != nil {
		if x, ok := x.Settings.(*PBRequest_SpeedSettings); ok {
			return x.SpeedSettings
		}
	}
	return nil
}

type isPBRequest_Settings interface {
	isPBRequest_Settings()
}

type PBRequest_LatencySettings struct {
	LatencySettings *PBLatencyTestSettings `protobuf:"bytes,5,opt,name=latency_settings,json=latencySettings,proto3,oneof"`
}

type PBRequest_SpeedSettings struct {
	SpeedSettings *PBSpeedTestSettings `protobuf:"bytes,6,opt,name=speed_settings,json=speedSettings,proto3,oneof"`
}

func (*PBRequest_LatencySettings) isPBRequest_Settings() {}

func (*PBRequest_SpeedSettings) isPBRequest_Settings() {}

var File_worker_protocol_proto protoreflect.FileDescriptor

const file_worker_protocol_proto_rawDesc = "" +
	"\n" +
	"\x15worker/protocol.proto\x12\x06worker\":\n" +
	"\n" +
	"PBCoreInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\";\n" +
	"\x11PBValidationError\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\fR\x03tag\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xdd\x01\n" +
	"\n" +
	"PBResponse\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.worker.PBResponseTypeR\x04type\x12F\n" +
	"\x11validation_errors\x18\x02 \x03(\v2\x19.worker.PBValidationErrorR\x10validationErrors\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\fR\x03tag\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x05 \x01(\x03R\tlatencyMs\x12\x14\n" +
	"\x05speed\x18\x06 \x01(\x01R\x05speed\"\x9a\x01\n" +
	"\x15PBLatencyTestSettings\x12\x19\n" +
	"\btest_url\x18\x01 \x01(\tR\atestUrl\x12\x1f\n" +
	"\vraw_request\x18\x02 \x01(\fR\n" +
	"rawRequest\x12#\n" +
	"\rtimeout_nanos\x18\x03 \x01(\x03R\ftimeoutNanos\x12 \n" +
	"\vconcurrency\x18\x04 \x01(\x05R\vconcurrency\"\xe8\x01\n" +
	"\x13PBSpeedTestSettings\x12+\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x17.worker.PBSpeedTestModeR\x04mode\x12\x19\n" +
	"\btest_url\x18\x02 \x01(\tR\atestUrl\x12\x1f\n" +
	"\vraw_request\x18\x03 \x01(\fR\n" +
	"rawRequest\x12#\n" +
	"\rtimeout_nanos\x18\x04 \x01(\x03R\ftimeoutNanos\x12!\n" +
	"\ftarget_bytes\x18\x05 \x01(\x03R\vtargetBytes\x12 \n" +
	"\vconcurrency\x18\x06 \x01(\x05R\vconcurrency\">\n" +
	"\fPBObfsConfig\x12\x12\n" +
	"\x04type\x18\x01 \x01(\fR\x04type\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\fR\bpassword\"Y\n" +
	"\x0fPBVLESSSettings\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\x12\x12\n" +
	"\x04flow\x18\x02 \x01(\fR\x04flow\x12\x1e\n" +
	"\n" +
	"encryption\x18\x03 \x01(\fR\n" +
	"encryption\".\n" +
	"\x10PBTrojanSettings\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\fR\bpassword\"\\\n" +
	"\x0fPBVMessSettings\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\x12\x19\n" +
	"\balter_id\x18\x02 \x01(\x05R\aalterId\x12\x1a\n" +
	"\bsecurity\x18\x03 \x01(\fR\bsecurity\"K\n" +
	"\x15PBShadowsocksSettings\x12\x16\n" +
	"\x06method\x18\x01 \x01(\fR\x06method\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\fR\bpassword\"[\n" +
	"\x13PBHysteria2Settings\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\fR\bpassword\x12(\n" +
	"\x04obfs\x18\x02 \x01(\v2\x14.worker.PBObfsConfigR\x04obfs\"L\n" +
	"\x0fPBWireguardPeer\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\fR\bendpoint\"}\n" +
	"\x13PBWireguardSettings\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x01 \x01(\fR\tsecretKey\x12\x18\n" +
	"\aaddress\x18\x02 \x03(\fR\aaddress\x12-\n" +
	"\x05peers\x18\x03 \x03(\v2\x17.worker.PBWireguardPeerR\x05peers\"S\n" +
	"\x0fPBSocksSettings\x12\x18\n" +
	"\aversion\x18\x01 \x01(\fR\aversion\x12\x12\n" +
	"\x04user\x18\x02 \x01(\fR\x04user\x12\x12\n" +
	"\x04pass\x18\x03 \x01(\fR\x04pass\"8\n" +
	"\x0ePBHTTPSettings\x12\x12\n" +
	"\x04user\x18\x01 \x01(\fR\x04user\x12\x12\n" +
	"\x04pass\x18\x02 \x01(\fR\x04pass\"-\n" +
	"\x0fPBVLiteSettings\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\fR\bpassword\"f\n" +
	"\x0fPBRealityConfig\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12\x19\n" +
	"\bshort_id\x18\x02 \x01(\fR\ashortId\x12\x19\n" +
	"\bspider_x\x18\x03 \x01(\fR\aspiderX\"%\n" +
	"\vPBECHConfig\x12\x16\n" +
	"\x06config\x18\x01 \x03(\fR\x06config\"\xf4\x01\n" +
	"\vPBTLSConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1f\n" +
	"\vserver_name\x18\x02 \x01(\fR\n" +
	"serverName\x12\x1a\n" +
	"\binsecure\x18\x03 \x01(\bR\binsecure\x12\x12\n" +
	"\x04alpn\x18\x04 \x03(\fR\x04alpn\x12 \n" +
	"\vfingerprint\x18\x05 \x01(\fR\vfingerprint\x121\n" +
	"\areality\x18\x06 \x01(\v2\x17.worker.PBRealityConfigR\areality\x12%\n" +
	"\x03ech\x18\a \x01(\v2\x13.worker.PBECHConfigR\x03ech\"N\n" +
	"\fPBHTTPConfig\x12\x12\n" +
	"\x04host\x18\x01 \x03(\fR\x04host\x12\x12\n" +
	"\x04path\x18\x02 \x01(\fR\x04path\x12\x16\n" +
	"\x06method\x18\x03 \x01(\fR\x06method\";\n" +
	"\x11PBWebSocketConfig\x12\x12\n" +
	"\x04path\x18\x01 \x01(\fR\x04path\x12\x12\n" +
	"\x04host\x18\x02 \x01(\fR\x04host\"\x0e\n" +
	"\fPBQUICConfig\"1\n" +
	"\fPBGRPCConfig\x12!\n" +
	"\fservice_name\x18\x01 \x01(\fR\vserviceName\"=\n" +
	"\x13PBHTTPUpgradeConfig\x12\x12\n" +
	"\x04host\x18\x01 \x01(\fR\x04host\x12\x12\n" +
	"\x04path\x18\x02 \x01(\fR\x04path\"\xbd\x01\n" +
	"\rPBXHTTPConfig\x12\x12\n" +
	"\x04host\x18\x01 \x01(\fR\x04host\x12\x12\n" +
	"\x04path\x18\x02 \x01(\fR\x04path\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\fR\x04mode\x126\n" +
	"\x05extra\x18\x04 \x03(\v2 .worker.PBXHTTPConfig.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\";\n" +
	"\x11PBSplitHTTPConfig\x12\x12\n" +
	"\x04host\x18\x01 \x01(\fR\x04host\x12\x12\n" +
	"\x04path\x18\x02 \x01(\fR\x04path\"!\n" +
	"\vPBKCPConfig\x12\x12\n" +
	"\x04seed\x18\x01 \x01(\fR\x04seed\"\xac\x03\n" +
	"\x11PBTransportConfig\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12(\n" +
	"\x04http\x18\x02 \x01(\v2\x14.worker.PBHTTPConfigR\x04http\x127\n" +
	"\twebsocket\x18\x03 \x01(\v2\x19.worker.PBWebSocketConfigR\twebsocket\x12(\n" +
	"\x04quic\x18\x04 \x01(\v2\x14.worker.PBQUICConfigR\x04quic\x12(\n" +
	"\x04grpc\x18\x05 \x01(\v2\x14.worker.PBGRPCConfigR\x04grpc\x12>\n" +
	"\fhttp_upgrade\x18\x06 \x01(\v2\x1b.worker.PBHTTPUpgradeConfigR\vhttpUpgrade\x12+\n" +
	"\x05xhttp\x18\a \x01(\v2\x15.worker.PBXHTTPConfigR\x05xhttp\x128\n" +
	"\n" +
	"split_http\x18\b \x01(\v2\x19.worker.PBSplitHTTPConfigR\tsplitHttp\x12%\n" +
	"\x03kcp\x18\t \x01(\v2\x13.worker.PBKCPConfigR\x03kcp\"\xb3\x05\n" +
	"\x10PBOutboundConfig\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\fR\x03tag\x12\x12\n" +
	"\x04type\x18\x02 \x01(\fR\x04type\x12\x16\n" +
	"\x06server\x18\x03 \x01(\fR\x06server\x12\x12\n" +
	"\x04port\x18\x04 \x01(\rR\x04port\x12%\n" +
	"\x03tls\x18\x05 \x01(\v2\x13.worker.PBTLSConfigR\x03tls\x127\n" +
	"\ttransport\x18\x06 \x01(\v2\x19.worker.PBTransportConfigR\ttransport\x12/\n" +
	"\x05vless\x18\a \x01(\v2\x17.worker.PBVLESSSettingsH\x00R\x05vless\x122\n" +
	"\x06trojan\x18\b \x01(\v2\x18.worker.PBTrojanSettingsH\x00R\x06trojan\x12/\n" +
	"\x05vmess\x18\t \x01(\v2\x17.worker.PBVMessSettingsH\x00R\x05vmess\x12A\n" +
	"\vshadowsocks\x18\n" +
	" \x01(\v2\x1d.worker.PBShadowsocksSettingsH\x00R\vshadowsocks\x12;\n" +
	"\thysteria2\x18\v \x01(\v2\x1b.worker.PBHysteria2SettingsH\x00R\thysteria2\x12;\n" +
	"\twireguard\x18\f \x01(\v2\x1b.worker.PBWireguardSettingsH\x00R\twireguard\x12/\n" +
	"\x05socks\x18\r \x01(\v2\x17.worker.PBSocksSettingsH\x00R\x05socks\x12,\n" +
	"\x04http\x18\x0e \x01(\v2\x16.worker.PBHTTPSettingsH\x00R\x04http\x12/\n" +
	"\x05vlite\x18\x0f \x01(\v2\x17.worker.PBVLiteSettingsH\x00R\x05vliteB\n" +
	"\n" +
	"\bsettings\"\xcd\x02\n" +
	"\tPBRequest\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.worker.PBRequestTypeR\x04type\x12/\n" +
	"\ttest_type\x18\x02 \x01(\x0e2\x12.worker.PBTestTypeR\btestType\x122\n" +
	"\aconfigs\x18\x03 \x03(\v2\x18.worker.PBOutboundConfigR\aconfigs\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\fR\x04tags\x12J\n" +
	"\x10latency_settings\x18\x05 \x01(\v2\x1d.worker.PBLatencyTestSettingsH\x00R\x0flatencySettings\x12D\n" +
	"\x0espeed_settings\x18\x06 \x01(\v2\x1b.worker.PBSpeedTestSettingsH\x00R\rspeedSettingsB\n" +
	"\n" +
	"\bsettings*P\n" +
	"\rPBRequestType\x12\x17\n" +
	"\x13REQUEST_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10REQUEST_VALIDATE\x10\x01\x12\x10\n" +
	"\fREQUEST_TEST\x10\x02*D\n" +
	"\n" +
	"PBTestType\x12\x14\n" +
	"\x10TEST_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fTEST_LATENCY\x10\x01\x12\x0e\n" +
	"\n" +
	"TEST_SPEED\x10\x02*\x92\x01\n" +
	"\x0ePBResponseType\x12\x18\n" +
	"\x14RESPONSE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13RESPONSE_VALIDATION\x10\x01\x12\x13\n" +
	"\x0fRESPONSE_RESULT\x10\x02\x12\x12\n" +
	"\x0eRESPONSE_ERROR\x10\x03\x12\x11\n" +
	"\rRESPONSE_BUSY\x10\x04\x12\x11\n" +
	"\rRESPONSE_DONE\x10\x05*N\n" +
	"\x0fPBSpeedTestMode\x12\x15\n" +
	"\x11SPEED_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSPEED_DOWNLOAD\x10\x01\x12\x10\n" +
	"\fSPEED_UPLOAD\x10\x02B4Z2github.com/bluegradienthorizon/proxytoolbox/workerb\x06proto3"

var (
	file_worker_protocol_proto_rawDescOnce sync.Once
	file_worker_protocol_proto_rawDescData []byte
)

func file_worker_protocol_proto_rawDescGZIP() []byte {
	file_worker_protocol_proto_rawDescOnce.Do(func() {
		file_worker_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_protocol_proto_rawDesc), len(file_worker_protocol_proto_rawDesc)))
	})
	return file_worker_protocol_proto_rawDescData
}

var file_worker_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_worker_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_worker_protocol_proto_goTypes = []any{
	(PBRequestType)(0),            // 0: worker.PBRequestType
	(PBTestType)(0),               // 1: worker.PBTestType
	(PBResponseType)(0),           // 2: worker.PBResponseType
	(PBSpeedTestMode)(0),          // 3: worker.PBSpeedTestMode
	(*PBCoreInfo)(nil),            // 4: worker.PBCoreInfo
	(*PBValidationError)(nil),     // 5: worker.PBValidationError
	(*PBResponse)(nil),            // 6: worker.PBResponse
	(*PBLatencyTestSettings)(nil), // 7: worker.PBLatencyTestSettings
	(*PBSpeedTestSettings)(nil),   // 8: worker.PBSpeedTestSettings
	(*PBObfsConfig)(nil),          // 9: worker.PBObfsConfig
	(*PBVLESSSettings)(nil),       // 10: worker.PBVLESSSettings
	(*PBTrojanSettings)(nil),      // 11: worker.PBTrojanSettings
	(*PBVMessSettings)(nil),       // 12: worker.PBVMessSettings
	(*PBShadowsocksSettings)(nil), // 13: worker.PBShadowsocksSettings
	(*PBHysteria2Settings)(nil),   // 14: worker.PBHysteria2Settings
	(*PBWireguardPeer)(nil),       // 15: worker.PBWireguardPeer
	(*PBWireguardSettings)(nil),   // 16: worker.PBWireguardSettings
	(*PBSocksSettings)(nil),       // 17: worker.PBSocksSettings
	(*PBHTTPSettings)(nil),        // 18: worker.PBHTTPSettings
	(*PBVLiteSettings)(nil),       // 19: worker.PBVLiteSettings
	(*PBRealityConfig)(nil),       // 20: worker.PBRealityConfig
	(*PBECHConfig)(nil),           // 21: worker.PBECHConfig
	(*PBTLSConfig)(nil),           // 22: worker.PBTLSConfig
	(*PBHTTPConfig)(nil),          // 23: worker.PBHTTPConfig
	(*PBWebSocketConfig)(nil),     // 24: worker.PBWebSocketConfig
	(*PBQUICConfig)(nil),          // 25: worker.PBQUICConfig
	(*PBGRPCConfig)(nil),          // 26: worker.PBGRPCConfig
	(*PBHTTPUpgradeConfig)(nil),   // 27: worker.PBHTTPUpgradeConfig
	(*PBXHTTPConfig)(nil),         // 28: worker.PBXHTTPConfig
	(*PBSplitHTTPConfig)(nil),     // 29: worker.PBSplitHTTPConfig
	(*PBKCPConfig)(nil),           // 30: worker.PBKCPConfig
	(*PBTransportConfig)(nil),     // 31: worker.PBTransportConfig
	(*PBOutboundConfig)(nil),      // 32: worker.PBOutboundConfig
	(*PBRequest)(nil),             // 33: worker.PBRequest
	nil,                           // 34: worker.PBXHTTPConfig.ExtraEntry
}
var file_worker_protocol_proto_depIdxs = []int32{
	2,  // 0: worker.PBResponse.type:type_name -> worker.PBResponseType
	5,  // 1: worker.PBResponse.validation_errors:type_name -> worker.PBValidationError
	3,  // 2: worker.PBSpeedTestSettings.mode:type_name -> worker.PBSpeedTestMode
	9,  // 3: worker.PBHysteria2Settings.obfs:type_name -> worker.PBObfsConfig
	15, // 4: worker.PBWireguardSettings.peers:type_name -> worker.PBWireguardPeer
	20, // 5: worker.PBTLSConfig.reality:type_name -> worker.PBRealityConfig
	21, // 6: worker.PBTLSConfig.ech:type_name -> worker.PBECHConfig
	34, // 7: worker.PBXHTTPConfig.extra:type_name -> worker.PBXHTTPConfig.ExtraEntry
	23, // 8: worker.PBTransportConfig.http:type_name -> worker.PBHTTPConfig
	24, // 9: worker.PBTransportConfig.websocket:type_name -> worker.PBWebSocketConfig
	25, // 10: worker.PBTransportConfig.quic:type_name -> worker.PBQUICConfig
	26, // 11: worker.PBTransportConfig.grpc:type_name -> worker.PBGRPCConfig
	27, // 12: worker.PBTransportConfig.http_upgrade:type_name -> worker.PBHTTPUpgradeConfig
	28, // 13: worker.PBTransportConfig.xhttp:type_name -> worker.PBXHTTPConfig
	29, // 14: worker.PBTransportConfig.split_http:type_name -> worker.PBSplitHTTPConfig
	30, // 15: worker.PBTransportConfig.kcp:type_name -> worker.PBKCPConfig
	22, // 16: worker.PBOutboundConfig.tls:type_name -> worker.PBTLSConfig
	31, // 17: worker.PBOutboundConfig.transport:type_name -> worker.PBTransportConfig
	10, // 18: worker.PBOutboundConfig.vless:type_name -> worker.PBVLESSSettings
	11, // 19: worker.PBOutboundConfig.trojan:type_name -> worker.PBTrojanSettings
	12, // 20: worker.PBOutboundConfig.vmess:type_name -> worker.PBVMessSettings
	13, // 21: worker.PBOutboundConfig.shadowsocks:type_name -> worker.PBShadowsocksSettings
	14, // 22: worker.PBOutboundConfig.hysteria2:type_name -> worker.PBHysteria2Settings
	16, // 23: worker.PBOutboundConfig.wireguard:type_name -> worker.PBWireguardSettings
	17, // 24: worker.PBOutboundConfig.socks:type_name -> worker.PBSocksSettings
	18, // 25: worker.PBOutboundConfig.http:type_name -> worker.PBHTTPSettings
	19, // 26: worker.PBOutboundConfig.vlite:type_name -> worker.PBVLiteSettings
	0,  // 27: worker.PBRequest.type:type_name -> worker.PBRequestType
	1,  // 28: worker.PBRequest.test_type:type_name -> worker.PBTestType
	32, // 29: worker.PBRequest.configs:type_name -> worker.PBOutboundConfig
	7,  // 30: worker.PBRequest.latency_settings:type_name -> worker.PBLatencyTestSettings
	8,  // 31: worker.PBRequest.speed_settings:type_name -> worker.PBSpeedTestSettings
	32, // [32:32] is the sub-list for method output_type
	32, // [32:32] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_worker_protocol_proto_init() }
func file_worker_protocol_proto_init() {
	if File_worker_protocol_proto != nil {
		return
	}
	file_worker_protocol_proto_msgTypes[28].OneofWrappers = []any{
		(*PBOutboundConfig_Vless)(nil),
		(*PBOutboundConfig_Trojan)(nil),
		(*PBOutboundConfig_Vmess)(nil),
		(*PBOutboundConfig_Shadowsocks)(nil),
		(*PBOutboundConfig_Hysteria2)(nil),
		(*PBOutboundConfig_Wireguard)(nil),
		(*PBOutboundConfig_Socks)(nil),
		(*PBOutboundConfig_Http)(nil),
		(*PBOutboundConfig_Vlite)(nil),
	}
	file_worker_protocol_proto_msgTypes[29].OneofWrappers = []any{
		(*PBRequest_LatencySettings)(nil),
		(*PBRequest_SpeedSettings)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_protocol_proto_rawDesc), len(file_worker_protocol_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_worker_protocol_proto_goTypes,
		DependencyIndexes: file_worker_protocol_proto_depIdxs,
		EnumInfos:         file_worker_protocol_proto_enumTypes,
		MessageInfos:      file_worker_protocol_proto_msgTypes,
	}.Build()
	File_worker_protocol_proto = out.File
	file_worker_protocol_proto_goTypes = nil
	file_worker_protocol_proto_depIdxs = nil
}
